# Usa una imagen base de Node.js
FROM node:20


# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Construye la aplicación Next.js
RUN npm run build

# Expone el puerto en el que Next.js escuchará
EXPOSE 3000

# Comando para correr la aplicación en modo producción
CMD ["npm", "run", "dev"]
